### ISSUE TITLE
error: could not find function "coloc.abf

### ISSUE THREAD

**Issue by psychrb** [clagiamba/moloc#2]
In running coloc.genome, error received:
Error in { : task 1 failed - "could not find function "coloc.abf"
**How to resolve?**

Error even for running sample:
res<-coloc.genome(data_genome,bed,prefix="pref",save.SNP.info=FALSE, cores=20, have_alleles=TRUE, bychrpos=TRUE, prior_var="default", priors=c(1e-04, 1e-06, 1e-07), min_nsnps = 50, takelog = FALSE, write=TRUE, outfolder = "test", forcePVAL = FALSE)

Running in parallel
Looping through 231 regions
Error in { : task 1 failed - "could not find function "coloc.abf""

**Comment by psychrb** [comment]
Using R3.6.3

**Comment by bkupmc** [comment]
Ran into the same problem. A search showed that coloc.abf is part of package coloc.

Solution is to download coloc from CRAN and load this library as well.

Best

**Comment by psychrb** [comment]
This doesn't solve the problem. I also load coloc library and run...I get the very same error..
> res<-coloc.genome(data_genome,bed,prefix="pref",save.SNP.info=FALSE, 
+                   cores=20, have_alleles=TRUE, bychrpos=TRUE, 
+                   prior_var="default", priors=c(1e-04, 1e-06, 1e-07), 
+                   min_nsnps = 50, takelog = FALSE, write=TRUE, 
+                   outfolder = "test", forcePVAL = FALSE)
Running in parallel
Looping through 231 regions
Error in { : task 1 failed - "could not find function "coloc.abf""

Libraries loaded:
library(moloc)
library(knitr)
library(coloc)
library(mvtnorm)
library(foreach)
library(doParallel)
library(data.table)
library(rmarkdown)
library(testthat)

**Comment by psychrb** [comment]
This doesn't solve the problem. When I load library(coloc), I get the very same error...
Error in { : task 1 failed - "could not find function "coloc.abf""
Loaded libraries:
library(moloc)
library(knitr)
library(coloc)
library(mvtnorm)
library(foreach)
library(doParallel)
library(data.table)
library(rmarkdown)
library(testthat)

**Comment by bkupmc** [comment]
Can you see if coloc.abf can be found in help, just to make sure that it is loaded?

**Comment by psychrb** [comment]
Great! Thanks! Resolved!
library(snpStats) also needed...
